import Head from "next/head";
import Navbar from "../components/navbar"
import Hero from "../components/hero"
import Steps from "../components/steps"
import Footer from "../components/footer"

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className="mt-16 mx-auto max-w-7xl px-4 sm:mt-24">
        <Hero />
        <Steps />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
